"""added created at to post model

Revision ID: 32e8e31b22b2
Revises: 62b74f50a96f
Create Date: 2024-12-08 00:50:03.765698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e8e31b22b2'
down_revision = '62b74f50a96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=1000), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
